---
- name: Update APT repository
  when:
    - nhc_upgrade
    - ansible_facts['os_family'] == 'Debian'
  ansible.builtin.apt:
    update_cache: true

- name: Install nhc
  ansible.builtin.package:
    name: "{{ nhc_packages }}"
    state: "{{ 'latest' if nhc_upgrade else 'present' }}"

- name: Configure nhc.conf
  when: nhc_config is defined
  ansible.builtin.template:
    src: nhc.conf.j2
    dest: /etc/nhc/nhc.conf
    owner: root
    group: root
    mode: "0640"

- name: Configure NHC variables
  when: nhc_variables is defined
  ansible.builtin.template:
    src: nhc.default.j2
    dest: /etc/default/nhc
    owner: root
    group: root
    mode: "0640"
