---
- name: Update APT repository
  when:
    - nhc_upgrade
    - ansible_facts['os_family'] == 'Debian'
  ansible.builtin.apt:
    update_cache: true

- name: Install nhc
  ansible.builtin.package:
    name: "{{ nhc_packages }}"
    state: "{{ 'latest' if nhc_upgrade else 'present' }}"

- name: Configure nhc.conf
  when: nhc_config is defined
  ansible.builtin.template:
    src: nhc.conf.j2
    dest: /etc/nhc/nhc.conf
    owner: root
    group: root
    mode: "0640"

- name: Configure NHC variables
  when: nhc_variables is defined
  ansible.builtin.template:
    src: nhc.default.j2
    dest: /etc/default/nhc
    owner: root
    group: root
    mode: "0640"

- name: Script to check and fix /etc/nhc/nhc.conf at boot
  when: nhc_boot_check_script is defined
  ansible.builtin.copy:
    dest: /etc/nhc/boot-check.sh
    content: "{{ nhc_boot_check_script }}"
    owner: root
    group: root
    mode: "0755"

- name: NHC boot check script unit file
  when: nhc_boot_check_script is defined
  ansible.builtin.copy:
    dest: /etc/systemd/system/nhc-boot-check.service
    content: "{{ nhc_boot_check_unit }}"
    owner: root
    group: root
    mode: "0644"

- name: Enable nhc-boot-check systemd service
  when: nhc_boot_check_script is defined
  ansible.builtin.systemd_service:
    name: nhc-boot-check
    daemon_reload: true
    enabled: true
